name: Renovate Bot CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Renovate Bot GitHub Action
      uses: renovatebot/github-action@v43.0.2
      with:
        token: ${{ secrets.RENOVATE_TOKEN }}
        configurationFile: renovate.json
        platform: github
        logLevel: debug